/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import model.ClienteDAO;
import model.DAO;
import model.Veterinario;
import model.VeterinarioDAO;



/**
 *
 * @author User PC
 */
public class TelaCadastroVeterinario extends javax.swing.JFrame {
public String especialidades="";


    /**
     * Creates new form TelaCadastroVeterinario
     */
    public TelaCadastroVeterinario() {
        initComponents();
        tableDados.getColumnModel().getColumn(5).setMinWidth(0);
        tableDados.getColumnModel().getColumn(5).setMaxWidth(0);
        
        comboEspecialidades.removeAllItems();
        comboEspecialidades.addItem("Cão");
        comboEspecialidades.addItem("Gato");
        comboEspecialidades.addItem("Cão e Gato");
    
        ImageIcon icon = new ImageIcon(DAO.getImage("consultaagendada"));// aqui vai ter que colocar o endereço do seu desktop
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel6.setIcon(scaledIcon);
        
        ImageIcon icon1 = new ImageIcon(DAO.getImage("novaconsulta"));// aqui vai ter que colocar o endereço do seu desktop
        Image img1 = icon1.getImage();
        Image imgScale1 = img1.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(imgScale1);
        jLabel7.setIcon(scaledIcon1);
        
        ImageIcon icon2 = new ImageIcon(DAO.getImage("cadastroanimal"));// aqui vai ter que colocar o endereço do seu desktop
        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(imgScale2);
        jLabel8.setIcon(scaledIcon2);
        
        ImageIcon icon3 = new ImageIcon(DAO.getImage("cadastrocliente"));// aqui vai ter que colocar o endereço do seu desktop
        Image img3 = icon3.getImage();
        Image imgScale3 = img3.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon3 = new ImageIcon(imgScale3);
        jLabel9.setIcon(scaledIcon3);
        
        ImageIcon icon4 = new ImageIcon(DAO.getImage("cadastroveterinario"));// aqui vai ter que colocar o endereço do seu desktop
        Image img4 = icon4.getImage();
        Image imgScale4 = img4.getScaledInstance(jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon4 = new ImageIcon(imgScale4);
        jLabel11.setIcon(scaledIcon4);
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro = new javax.swing.JLayeredPane();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelAnoNascimento = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        labelCliente = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        textCrvm = new javax.swing.JTextField();
        labelCliente1 = new javax.swing.JLabel();
        panelDados = new javax.swing.JScrollPane();
        tableDados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelCliente2 = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        comboEspecialidades = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        painelCadastro.setForeground(new java.awt.Color(255, 255, 255));
        painelCadastro.setOpaque(true);
        painelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNome.setText("Nome");
        painelCadastro.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        textNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 491, -1));

        labelAnoNascimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAnoNascimento.setText("CRVM");
        painelCadastro.add(labelAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        textEndereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(textEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 490, -1));

        labelCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCliente.setText("Especialidades");
        painelCadastro.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        buttonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        buttonSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSalvar.setForeground(new java.awt.Color(51, 255, 51));
        buttonSalvar.setText("Salvar");
        buttonSalvar.setOpaque(false);
        buttonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalvarMouseClicked(evt);
            }
        });
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        painelCadastro.add(buttonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, 50));

        textCrvm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(textCrvm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 180, -1));

        labelCliente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCliente1.setText("endereço");
        painelCadastro.add(labelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        tableDados.setModel(
            new VeterinarioTableModel((ArrayList)VeterinarioDAO.getInstance().getAllVeterinarios())
        );
        tableDados.setName("tableDados"); // NOI18N
        panelDados.setViewportView(tableDados);
        tableDados.getAccessibleContext().setAccessibleName("tableDados");

        painelCadastro.add(panelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 570, 130));

        jButton1.setText("DELETAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        painelCadastro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, 40));

        labelCliente2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCliente2.setText("Telefone");
        painelCadastro.add(labelCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        textTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(textTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 219, -1));

        comboEspecialidades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEspecialidades.setName("comboEspecialidades"); // NOI18N
        comboEspecialidades.setPreferredSize(new java.awt.Dimension(6, 28));
        comboEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecialidadesActionPerformed(evt);
            }
        });
        painelCadastro.add(comboEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, -1));
        comboEspecialidades.getAccessibleContext().setAccessibleName("comboEspecialidades");

        getContentPane().add(painelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 0, 688, 533));

        jPanel6.setBackground(new java.awt.Color(134, 207, 132));
        jPanel6.setForeground(new java.awt.Color(134, 207, 132));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Cadastros");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel32.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Consultas");
        jLabel32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel32KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultas Agendadas");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nova Consulta");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastro Animal");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastro Cliente");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cadastro Veterinario");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel6.setText("jLabel6");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 40));

        jLabel7.setText("jLabel7");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, 40));

        jLabel8.setText("jLabel8");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 40, 40));

        jLabel9.setText("jLabel9");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 274, 40, 40));

        jLabel11.setText("jLabel11");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarMouseClicked


        Integer id = VeterinarioDAO.getInstance().addVeterinario(
               textNome.getText(), 
               textEndereco.getText(),
               textTelefone.getText(),
               textCrvm.getText(),
              (String)comboEspecialidades.getSelectedItem());
        
        if (id > -1) {
          Veterinario veterinario = VeterinarioDAO.getInstance().getVeterinarioById(id);
          VeterinarioTableModel tb = (VeterinarioTableModel)tableDados.getModel();
          tb.addItem(veterinario);
        }
        
    }//GEN-LAST:event_buttonSalvarMouseClicked

    private void comboEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspecialidadesActionPerformed

    private void jLabel32KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel32KeyPressed

    }//GEN-LAST:event_jLabel32KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        TelaConsultas tela = new TelaConsultas();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TelaCadastroConsulta tela = new TelaCadastroConsulta();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        TelaCadastroAnimal tela = new TelaCadastroAnimal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TelaCadastroCliente tela = new TelaCadastroCliente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
           TelaCadastroVeterinario tela = new TelaCadastroVeterinario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        VeterinarioTableModel tb = ((VeterinarioTableModel)tableDados.getModel());
     
        int idVeterinario =(Integer) tableDados.getModel().getValueAt(tableDados.getSelectedRow(), 5);
       
        VeterinarioDAO.getInstance().deleteVeterinarioById(idVeterinario);
       
        tb.removeItem(tableDados.getSelectedRow());         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox<String> comboEspecialidades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelAnoNascimento;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelCliente1;
    private javax.swing.JLabel labelCliente2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLayeredPane painelCadastro;
    private javax.swing.JScrollPane panelDados;
    private javax.swing.JTable tableDados;
    private javax.swing.JTextField textCrvm;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
