/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import model.Consulta;
import model.ConsultaDAO;
import model.Veterinario;
import model.VeterinarioDAO;
import view.TelaCadastroCliente;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import model.DAO;
import model.ExameDAO;

/**
 *
 * @author karlos
 */
public class TelaRealizaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TelaAnimais
     */
    public TelaRealizaConsulta() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(DAO.getImage("consultaagendada"));// aqui vai ter que colocar o endereço do seu desktop
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel9.setIcon(scaledIcon);
        
        ImageIcon icon1 = new ImageIcon(DAO.getImage("novaconsulta"));// aqui vai ter que colocar o endereço do seu desktop
        Image img1 = icon1.getImage();
        Image imgScale1 = img1.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(imgScale1);
        jLabel10.setIcon(scaledIcon1);
        
         ImageIcon icon2 = new ImageIcon(DAO.getImage("cadastroanimal"));// aqui vai ter que colocar o endereço do seu desktop
        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(jLabel11.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(imgScale2);
        jLabel11.setIcon(scaledIcon2);
        
        ImageIcon icon3 = new ImageIcon(DAO.getImage("cadastrocliente"));// aqui vai ter que colocar o endereço do seu desktop
        Image img3 = icon3.getImage();
        Image imgScale3 = img3.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon3 = new ImageIcon(imgScale3);
        jLabel13.setIcon(scaledIcon3);
        
        ImageIcon icon4 = new ImageIcon(DAO.getImage("cadastroveterinario"));// aqui vai ter que colocar o endereço do seu desktop
        Image img4 = icon4.getImage();
        Image imgScale4 = img4.getScaledInstance(jLabel14.getWidth(), jLabel14.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon4 = new ImageIcon(imgScale4);
        jLabel14.setIcon(scaledIcon4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        painelCadastro = new javax.swing.JLayeredPane();
        labelData = new javax.swing.JLabel();
        vet = new javax.swing.JTextField();
        labelHistorico = new javax.swing.JLabel();
        historico = new javax.swing.JTextField();
        labelExames = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        labelAnimal = new javax.swing.JLabel();
        labelCRVM = new javax.swing.JLabel();
        exames = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        animal = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        inserirExames = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(134, 207, 132));
        jPanel1.setForeground(new java.awt.Color(134, 207, 132));
        jPanel1.setPreferredSize(new java.awt.Dimension(1058, 450));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastros");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consultas");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Consultas agendadas");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastro cliente");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Nova consulta");
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadastro animal");
        jLabel6.setToolTipText("");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cadastro veterinario");
        jLabel12.setToolTipText("");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        painelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        painelCadastro.setForeground(new java.awt.Color(255, 255, 255));
        painelCadastro.setOpaque(true);
        painelCadastro.setPreferredSize(new java.awt.Dimension(700, 430));
        painelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelData.setText("Data");
        painelCadastro.add(labelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        vet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vet.setEnabled(false);
        vet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetActionPerformed(evt);
            }
        });
        painelCadastro.add(vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 190, -1));

        labelHistorico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHistorico.setText("Historico");
        painelCadastro.add(labelHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        historico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 510, 90));

        labelExames.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelExames.setText("Exames");
        painelCadastro.add(labelExames, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCliente.setText("Cliente");
        painelCadastro.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        buttonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        buttonSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSalvar.setForeground(new java.awt.Color(51, 255, 51));
        buttonSalvar.setText("Finalizar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        painelCadastro.add(buttonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 127, 40));

        labelAnimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAnimal.setText("Animal");
        painelCadastro.add(labelAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        labelCRVM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCRVM.setText("Veterinário");
        painelCadastro.add(labelCRVM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        exames.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelCadastro.add(exames, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 160, -1));

        data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        data.setEnabled(false);
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        painelCadastro.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, -1));

        animal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        animal.setEnabled(false);
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });
        painelCadastro.add(animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, -1));

        cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cliente.setEnabled(false);
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        painelCadastro.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 190, -1));

        jLabel8.setText("jLabel8");
        painelCadastro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabel7.setText("jLabel7");
        painelCadastro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jTable1.setModel(new ExameTableModel(new ArrayList()));
        jScrollPane1.setViewportView(jTable1);

        painelCadastro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 170));

        inserirExames.setText("Inserir Exame");
        inserirExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirExamesActionPerformed(evt);
            }
        });
        painelCadastro.add(inserirExames, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(painelCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel4.getAccessibleContext().setAccessibleName("jButton4");
        painelCadastro.getAccessibleContext().setAccessibleName("PainelCadastro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if (consulta == null)
            return;
        
        consulta.setHistorico(historico.getText());
        consulta.setListaDeExames(exames.getText());
        
        ConsultaDAO.getInstance().finalizar(consulta);
        
        TelaConsultas consulta = new TelaConsultas();
        consulta.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void vetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vetActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        TelaCadastroAnimal nomeVariavel = new TelaCadastroAnimal();
        nomeVariavel.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TelaCadastroCliente nomeVariavel = new TelaCadastroCliente();
        nomeVariavel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        TelaConsultas nomeVariavel = new TelaConsultas();
        nomeVariavel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        TelaCadastroVeterinario nomeVariavel = new TelaCadastroVeterinario();
        nomeVariavel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    Consulta consulta = null;
    
    void setConsultaId(Integer id) {
        consulta = ConsultaDAO.getInstance().getConsultaById(id);
        
        if (consulta == null)
            return;
        
        data.setText(consulta.getData());
        
        cliente.setText(consulta.getIdCliente().getNome());
        
        Veterinario veterinario = VeterinarioDAO.getInstance()
                .getVeterinarioByCrvm(consulta.getCRVM());
        vet.setText(veterinario.getNome());
        
        animal.setText(consulta.getIdAnimal().getNome());
        
        historico.setText(consulta.getHistorico());

        exames.setText(consulta.getListaDeExames());
        
        pegarExames();
    }
    
    void pegarExames (){
        
        jTable1.setModel(new ExameTableModel((ArrayList)ExameDAO.getInstance().getExamesByConsulta(consulta.getId())));
  
    }
    
    class hora implements ActionListener{
        public void actionPerformed(ActionEvent e){
            Calendar now=Calendar.getInstance();
            jLabel8.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Date dataSistema=new Date();
        SimpleDateFormat formato=new SimpleDateFormat("dd/MM/yyyy");
        jLabel7.setText(formato.format(dataSistema));
        
        
        Timer timer = new Timer(1000,new hora());
        timer.start();
     
    }//GEN-LAST:event_formWindowOpened

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void inserirExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirExamesActionPerformed
        ExameDAO.getInstance().addExame(exames.getText(), consulta);
        pegarExames();
    }//GEN-LAST:event_inserirExamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRealizaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRealizaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField animal;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField data;
    private javax.swing.JTextField exames;
    private javax.swing.JTextField historico;
    private javax.swing.JButton inserirExames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAnimal;
    private javax.swing.JLabel labelCRVM;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelExames;
    private javax.swing.JLabel labelHistorico;
    private javax.swing.JLayeredPane painelCadastro;
    private javax.swing.JTextField vet;
    // End of variables declaration//GEN-END:variables
}
